version: '3.7'
services:
  dashboard:
    build:
      context: seosnap-dashboard
    container_name: seosnap_stack_dashboard
    env_file: ./.env
    volumes:
      - ./logs:/code/logs
    networks:
      - seosnap

  cachewarmer:
    build:
      context: seosnap-cachewarmer
    container_name: seosnap_stack_cachewarmer
    env_file: ./.env
    volumes:
      - ./logs:/code/logs
    depends_on:
      - dashboard
      - rendertron
    networks:
      - seosnap

  rendertron:
    image: experiusnl/rendertron:3.2.1
    container_name: snapstack_rendertron
    env_file: ./.env
    restart: always
    volumes:
      - ./rendertron-config.json:/app/config.json
      - ./cache:/app/cache
    ports:
      - 3000:3000
    networks:
      - seosnap

  db:
    container_name: seosnap_stack_db
    env_file: ./.env
    volumes:
      - ./dev/instance/mariadb:/var/lib/mysql
    networks:
      - seosnap

networks:
  seosnap:
    driver: bridge
